# Generated by Django 2.2.5 on 2019-09-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='Name',
            new_name='FName',
        ),
        migrations.AlterField(
            model_name='people',
            name='Connections',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='people',
            name='Group',
            field=models.IntegerField(default=1),
        ),
    ]
