# Generated by Django 2.2.5 on 2019-09-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_auto_20190921_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='Connections',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='people',
            name='Group',
            field=models.CharField(max_length=1),
        ),
    ]
