# Generated by Django 2.2.5 on 2019-09-23 09:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0004_auto_20190921_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='Group',
        ),
        migrations.AddField(
            model_name='people',
            name='Group',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='People', to='charts.People'),
            preserve_default=False,
        ),
    ]
