# Generated by Django 2.2.5 on 2019-09-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0005_auto_20190923_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='Group',
        ),
        migrations.AddField(
            model_name='people',
            name='Group',
            field=models.ManyToManyField(related_name='_people_Group_+', to='charts.People'),
        ),
    ]
