# Generated by Django 2.2.5 on 2019-09-23 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0007_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Name',
            new_name='Names',
        ),
        migrations.RemoveField(
            model_name='people',
            name='Connections',
        ),
        migrations.RemoveField(
            model_name='people',
            name='FName',
        ),
        migrations.RemoveField(
            model_name='people',
            name='Group',
        ),
        migrations.AddField(
            model_name='people',
            name='Relation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='charts.Names'),
            preserve_default=False,
        ),
    ]
