# Generated by Django 2.2.5 on 2019-09-23 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0008_auto_20190923_0118'),
    ]

    operations = [
        migrations.CreateModel(
            name='First_Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Grouping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.First_Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='people',
            name='Relation',
        ),
        migrations.AddField(
            model_name='people',
            name='Connections',
            field=models.CharField(default='', editable=False, max_length=1),
        ),
        migrations.AddField(
            model_name='people',
            name='FName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='people',
            name='Group',
            field=models.ManyToManyField(related_name='_people_Group_+', to='charts.People'),
        ),
        migrations.DeleteModel(
            name='Names',
        ),
    ]
