# Generated by Django 2.2.5 on 2019-09-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0009_auto_20190923_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='Group',
            field=models.ManyToManyField(default='', related_name='_people_Group_+', to='charts.People'),
        ),
    ]
