# Generated by Django 2.2.5 on 2019-09-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0010_auto_20190923_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouping',
            name='names',
            field=models.CharField(default='', max_length=100),
        ),
    ]
