# Generated by Django 2.2.5 on 2019-09-23 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0011_grouping_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouping',
            name='Group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.People'),
        ),
    ]
