# Generated by Django 2.2.5 on 2019-09-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0012_auto_20190923_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='Group',
            field=models.ManyToManyField(default='', related_name='group', through='charts.Grouping', to='charts.People'),
        ),
    ]
