# Generated by Django 2.2.5 on 2019-09-23 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0013_auto_20190923_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouping',
            name='Group',
        ),
        migrations.RemoveField(
            model_name='grouping',
            name='names',
        ),
        migrations.AddField(
            model_name='grouping',
            name='Connections',
            field=models.CharField(default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='grouping',
            name='From_Group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='fromgroup', to='charts.People'),
        ),
        migrations.AddField(
            model_name='grouping',
            name='To_Group',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='togroup', to='charts.People'),
        ),
    ]
