# Generated by Django 2.2.5 on 2019-09-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0014_auto_20190923_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='Group',
            field=models.ManyToManyField(default='', related_name='_people_Group_+', through='charts.Grouping', to='charts.People'),
        ),
    ]
