# Generated by Django 2.2.5 on 2019-09-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0015_auto_20190923_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouping',
            name='Connections',
            field=models.IntegerField(choices=[(1, 'CONNECTED'), (2, 'UNCONNECTED')]),
        ),
    ]
