# Generated by Django 2.2.5 on 2019-09-23 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0017_auto_20190923_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouping',
            name='To_Group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='togroup', to='charts.People'),
        ),
    ]
